#!/usr/bin/env bash

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Uso: git fork <original> <nuevo>"
    exit 1
fi

ORIGINAL="$1"
NEW="$2"

METHOD=$(gum choose \
    "GitHub fork (gh)" \
    "Git clone manual")

NAME=$(basename "$NEW" .git)

case "$METHOD" in

"GitHub fork (gh)")
    gh repo fork "$ORIGINAL" --clone=false
    git clone "$NEW"
    ;;

"Git clone manual")
    git clone "$ORIGINAL" "$NAME"

    cd "$NAME"

    git remote rename origin upstream
    git remote add origin "$NEW"

    echo "Fork creado"
    git remote -v
    ;;

esac
